concatenate issue resolved in final versions of scripts
There is an issue with concatenation of string and float objects.  Made
a change from + to , in all three scripts for this one line.  Error
below:
print("Time elapsed: " + totalTime)
TypeError: cannot concatenate 'str' and 'float' objects